version: "3.9"
services:
  db:
    image: postgres:17
    container_name: catdb
    environment:
      POSTGRES_DB: catdb
      POSTGRES_USER: catuser
      POSTGRES_PASSWORD: catpass
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "catuser", "-d", "catdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: catapi
    depends_on:
      db:
        condition: service_healthy
    # When using local Postgres, start the db profile: `docker compose --profile local up`
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg2://catuser:catpass@db:5432/catdb}
      DB_USER: ${DB_USER:-catuser}
      DB_PASSWORD: ${DB_PASSWORD:-catpass}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-catdb}
      PORT: 5000
      PYTHONUNBUFFERED: "1"
      UPLOAD_DIR: /app/uploads
    ports:
      - "5050:5000"
    volumes:
      - ./uploads:/app/uploads
    command: ["python", "main.py"]

volumes:
  dbdata:
