version: "3.9"
services:
  db:
    image: postgres:17
    container_name: catdb
    environment:
      POSTGRES_DB: catdb
      POSTGRES_USER: catuser
      POSTGRES_PASSWORD: catpass
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "catuser", "-d", "catdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      target: dev
    container_name: catapi
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: catuser
      DB_PASSWORD: catpass
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: catdb
      PORT: 5000
      PYTHONUNBUFFERED: "1"
      UPLOAD_DIR: /app/uploads
      # S3 Configuration (optional - falls back to local storage if not set)
      AWS_REGION: ${AWS_REGION:-}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      S3_BUCKET: ${S3_BUCKET:-}
      MAX_UPLOAD_MB: ${MAX_UPLOAD_MB:-10}
    ports:
      - "5050:5000"
    volumes:
      - ./src:/app/src
      - ./main.py:/app/main.py
      - ./uploads:/app/uploads
    command: ["python", "main.py"]

  pgadmin:
    image: dpage/pgadmin4
    container_name: cat-pgadmin
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
    ports:
      - "5051:80"

volumes:
  dbdata:
